/// Extracts an ISO 3166-1 alpha-2 country code from a node name.
///
/// Matches common English and Chinese country names, as well as
/// common prefixes like "us-", "jp-", etc.
/// Returns `null` if no country can be identified.
String? extractCountryCode(String nodeName) {
  final name = nodeName.toLowerCase();
  const map = {
    'us': ['美国', 'usa', 'united states', 'us-', 'us '],
    'jp': ['日本', 'japan', 'jp-', 'jp '],
    'cn': ['中国', 'china', 'cn-', 'cn '],
    'hk': ['香港', 'hong kong', 'hk-', 'hk '],
    'tw': ['台湾', 'taiwan', 'tw-', 'tw '],
    'sg': ['新加坡', 'singapore', 'sg-', 'sg '],
    'kr': ['韩国', 'korea', 'kr-', 'kr '],
    'gb': ['英国', 'uk', 'united kingdom', 'gb-', 'gb '],
    'de': ['德国', 'germany', 'de-', 'de '],
    'fr': ['法国', 'france', 'fr-', 'fr '],
    'ru': ['俄罗斯', 'russia', 'ru-', 'ru '],
    'au': ['澳大利亚', 'australia', 'au-', 'au '],
    'ca': ['加拿大', 'canada', 'ca-', 'ca '],
    'nl': ['荷兰', 'netherlands', 'nl-', 'nl '],
    'in': ['印度', 'india', 'in-', 'in '],
    'br': ['巴西', 'brazil', 'br-', 'br '],
    'it': ['意大利', 'italy', 'it-', 'it '],
    'es': ['西班牙', 'spain', 'es-', 'es '],
    'th': ['泰国', 'thailand', 'th-', 'th '],
    'my': ['马来西亚', 'malaysia', 'my-', 'my '],
    'ph': ['菲律宾', 'philippines', 'ph-', 'ph '],
    'id': ['印尼', 'indonesia', 'id-', 'id '],
    'vn': ['越南', 'vietnam', 'vn-', 'vn '],
    'tr': ['土耳其', 'turkey', 'tr-', 'tr '],
    'ae': ['阿联酋', 'uae', 'ae-', 'ae '],
    'il': ['以色列', 'israel', 'il-', 'il '],
    'za': ['南非', 'south africa', 'za-', 'za '],
    'mx': ['墨西哥', 'mexico', 'mx-', 'mx '],
    'ar': ['阿根廷', 'argentina', 'ar-', 'ar '],
    'ch': ['瑞士', 'switzerland', 'ch-', 'ch '],
    'se': ['瑞典', 'sweden', 'se-', 'se '],
    'no': ['挪威', 'norway', 'no-', 'no '],
    'fi': ['芬兰', 'finland', 'fi-', 'fi '],
    'dk': ['丹麦', 'denmark', 'dk-', 'dk '],
    'pl': ['波兰', 'poland', 'pl-', 'pl '],
    'cz': ['捷克', 'czech', 'cz-', 'cz '],
    'at': ['奥地利', 'austria', 'at-', 'at '],
    'be': ['比利时', 'belgium', 'be-', 'be '],
    'pt': ['葡萄牙', 'portugal', 'pt-', 'pt '],
    'gr': ['希腊', 'greece', 'gr-', 'gr '],
    'ie': ['爱尔兰', 'ireland', 'ie-', 'ie '],
    'nz': ['新西兰', 'new zealand', 'nz-', 'nz '],
    'eg': ['埃及', 'egypt', 'eg-', 'eg '],
    'sa': ['沙特', 'saudi', 'sa-', 'sa '],
    'qa': ['卡塔尔', 'qatar', 'qa-', 'qa '],
    'kw': ['科威特', 'kuwait', 'kw-', 'kw '],
    'bh': ['巴林', 'bahrain', 'bh-', 'bh '],
    'om': ['阿曼', 'oman', 'om-', 'om '],
    'pk': ['巴基斯坦', 'pakistan', 'pk-', 'pk '],
    'bd': ['孟加拉', 'bangladesh', 'bd-', 'bd '],
    'lk': ['斯里兰卡', 'sri lanka', 'lk-', 'lk '],
    'np': ['尼泊尔', 'nepal', 'np-', 'np '],
    'mm': ['缅甸', 'myanmar', 'mm-', 'mm '],
    'kh': ['柬埔寨', 'cambodia', 'kh-', 'kh '],
    'la': ['老挝', 'laos', 'la-', 'la '],
    'mn': ['蒙古', 'mongolia', 'mn-', 'mn '],
    'kz': ['哈萨克斯坦', 'kazakhstan', 'kz-', 'kz '],
    'uz': ['乌兹别克', 'uzbekistan', 'uz-', 'uz '],
    'ua': ['乌克兰', 'ukraine', 'ua-', 'ua '],
    'by': ['白俄罗斯', 'belarus', 'by-', 'by '],
    'ro': ['罗马尼亚', 'romania', 'ro-', 'ro '],
    'bg': ['保加利亚', 'bulgaria', 'bg-', 'bg '],
    'hu': ['匈牙利', 'hungary', 'hu-', 'hu '],
    'rs': ['塞尔维亚', 'serbia', 'rs-', 'rs '],
    'hr': ['克罗地亚', 'croatia', 'hr-', 'hr '],
    'sk': ['斯洛伐克', 'slovakia', 'sk-', 'sk '],
    'si': ['斯洛文尼亚', 'slovenia', 'si-', 'si '],
    'lt': ['立陶宛', 'lithuania', 'lt-', 'lt '],
    'lv': ['拉脱维亚', 'latvia', 'lv-', 'lv '],
    'ee': ['爱沙尼亚', 'estonia', 'ee-', 'ee '],
    'is': ['冰岛', 'iceland', 'is-', 'is '],
    'lu': ['卢森堡', 'luxembourg', 'lu-', 'lu '],
    'mt': ['马耳他', 'malta', 'mt-', 'mt '],
    'cy': ['塞浦路斯', 'cyprus', 'cy-', 'cy '],
    'cl': ['智利', 'chile', 'cl-', 'cl '],
    'pe': ['秘鲁', 'peru', 'pe-', 'pe '],
    'co': ['哥伦比亚', 'colombia', 'co-', 'co '],
    've': ['委内瑞拉', 'venezuela', 've-', 've '],
    'ec': ['厄瓜多尔', 'ecuador', 'ec-', 'ec '],
    'uy': ['乌拉圭', 'uruguay', 'uy-', 'uy '],
    'py': ['巴拉圭', 'paraguay', 'py-', 'py '],
    'bo': ['玻利维亚', 'bolivia', 'bo-', 'bo '],
    'ng': ['尼日利亚', 'nigeria', 'ng-', 'ng '],
    'ke': ['肯尼亚', 'kenya', 'ke-', 'ke '],
    'gh': ['加纳', 'ghana', 'gh-', 'gh '],
    'tz': ['坦桑尼亚', 'tanzania', 'tz-', 'tz '],
    'ug': ['乌干达', 'uganda', 'ug-', 'ug '],
    'et': ['埃塞俄比亚', 'ethiopia', 'et-', 'et '],
    'ma': ['摩洛哥', 'morocco', 'ma-', 'ma '],
    'tn': ['突尼斯', 'tunisia', 'tn-', 'tn '],
    'dz': ['阿尔及利亚', 'algeria', 'dz-', 'dz '],
    'ly': ['利比亚', 'libya', 'ly-', 'ly '],
    'sd': ['苏丹', 'sudan', 'sd-', 'sd '],
    'jo': ['约旦', 'jordan', 'jo-', 'jo '],
    'lb': ['黎巴嫩', 'lebanon', 'lb-', 'lb '],
    'sy': ['叙利亚', 'syria', 'sy-', 'sy '],
    'iq': ['伊拉克', 'iraq', 'iq-', 'iq '],
    'ir': ['伊朗', 'iran', 'ir-', 'ir '],
    'af': ['阿富汗', 'afghanistan', 'af-', 'af '],
  };
  for (final entry in map.entries) {
    for (final keyword in entry.value) {
      if (name.contains(keyword)) return entry.key;
    }
  }
  return null;
}
